// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN2zxoaxCilJT5ei_zzDObvR3QKGXibVw',
    appId: '1:300205196408:web:54bc59c5e19c9f1647598d',
    messagingSenderId: '300205196408',
    projectId: 'onco-801d9',
    authDomain: 'onco-801d9.firebaseapp.com',
    storageBucket: 'onco-801d9.appspot.com',
    measurementId: 'G-80PYB5816H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0dx8dGUnAvAIgCIUl6l5Jl3rcI8yt8vU',
    appId: '1:300205196408:android:a4ac1103b0d7d6b247598d',
    messagingSenderId: '300205196408',
    projectId: 'onco-801d9',
    storageBucket: 'onco-801d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCr-3BoQ1MaIPxufqCaKX7hKDLQk3Mm_4',
    appId: '1:300205196408:ios:0bb3fd676478e8c047598d',
    messagingSenderId: '300205196408',
    projectId: 'onco-801d9',
    storageBucket: 'onco-801d9.appspot.com',
    iosBundleId: 'com.example.onco.onco',
  );
}
